### ISSUE TITLE
Memoized function should expose a way to invalidate it

### ISSUE THREAD

**Issue by bengourley** [serby/uber-memoize#1]
Currently if you want to cache bust before TTL, you have to create a counter in your application, have a way of passing it in as part of the cache-key and re-memoize the function when the counter changes. I think this is quite user hostile for a use-case that is pretty ordinary.

I suggest the following API:

``` js
function slowFn(input, cb) {
  setTimeout(cb, 5000)
}

// Cache for one hour
var quickerFn = uberMemoize.memoize('slow-fn', slowFn, 1000 * 60 * 60)

// Something has changed, now I want to invalidate
// the cache and have the slow fn be called again
quickerFn.invalidate()
```

---

While on the topic of API design, I don't think the prototypal pattern works very well for this module seeing as it only has one method.

``` js
var createMemoizer = require('uber-memoize')
  , memoize = createMemoizer(uberCache)

memoize(id, fn, ttl)
```

vs

``` js
var UberMemoize = require('uber-memoize')
  , uberMemoize = new UberMemoize(uberCache)

uberMemoize.memoize(id, fn, ttl)
```

**Comment by serby** [comment]
I agree. But I'd use `.clear()` to keep the term inline with the underlying caching engine.

``` js
quickerFn.clear()
```

**Comment by serby** [comment]
The second point should really be another issue, but as it stands I agree, I had intended to add a number of extra functions `.list()` `.get(id')` `.clear(id)` `.stats(id)` not sure how I feel about them now.

**Comment by bengourley** [comment]
I would use `clear()` if I was using the `engine.clear()` method, but I don't want to clear the entire cache. I've just incremented an internal counter variable, as per our application logic.

> The second point should really be another issue, but as it stands I agree, I had intended to add a number of extra functions .list() .get(id') .clear(id) .stats(id) not sure how I feel about them now.

Yes, sorry about clobbering this issue. I was just having a bit of a brain dump.

**Comment by serby** [comment]
It wouldn't clear the whole cache just this memoized id's. The mechanic for invalidation is not important to the user. I'm going to use the counter method or the internal for `ubercache-memcache.clear()` because it is quicker in that instance.

**Comment by bengourley** [comment]
Ok, I've already implemented and have tests passing, just need to name it. Are you still in favour of `fn.clear()` vs `fn.invalidate()` for the counter method?

**Comment by serby** [comment]
If I'm going to drop the prototypal interface then it might as well be:

``` js
var memoize = require('uber-memoize')
  , quickFn = memoize(uberCache, id, fn, ttl)

```

**Comment by serby** [comment]
I'm going to add `.clear(pattern)`to uber-cache. So definitely `.clear()` I never want to have the conversation. "What's the difference between clear and invalidate?" "Oh they achieve the same thing, but internally they work differently"
